### ISSUE TITLE
Add factory method to response mapper A to return List[A]

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#309]
To both simplify and reuse mapping methods already defined in our response mappers, let's add a factory method that returns the list implementation of a given response type. For example,

```java
public class FooResponse { ... }
public class FoosResponse { ... } // Returns a collection of FooResponse

public final class FooResponseMapper {
  public static FooResponse map(@NonNull Bar bar) { ... }
  public static FoosResponse toFoosResponse(@NonNull List<Bar> bars) { ... }
}
```

In the above example, **class** `FooResponseMapper` defines mapping methods for `map(Bar)` and `toFoosResponse(List<Bar>)`, where an instances of FoosResponse can be created with `FooResponseMapper.toFoosResponse(bars)`

## Issues

- [x] Add DatasetResponse.toDatasetsResponse() #306
- [x] Add JobResponseMapper.toJobsResponse() #307
- [x] Add NamespaceResponseMapper.toNamespacesResponse() #308
