### ISSUE TITLE
API models

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#356]
The following are a set of clean up tasks specific to our [API models](https://github.com/MarquezProject/marquez/tree/master/src/main/java/marquez/api/models): 

## Issues

- [x] Remove `Create*` prefix from request payloads #353
- [x] Remove `@JsonProperty` #343
- [x] Clean up lombok annotations in API request models #354
- [x] Clean up lombok annotations in API response models #355 
- [x] Rename class Job #358 
- [x] Remove timestamp from the API models and replace with String type #189
