### ISSUE TITLE
Implement DatasourceUrn common model

### ISSUE THREAD

**Issue by sshah-wework** [MarquezProject/marquez#373]
We have a single URN parser that is designed to work with Datasets. There is a lot that can be re-used for Datasources, for example: validating the URN format and generating a valid URN from components. We should factor out what's common and use that in validating URNs for various types.

**Comment by sshah-wework** [comment]
- [ ] Extract a base Urn class from DatasetUrn
- [ ] Implement DatasourceUrn on top of the base Urn
- [ ] Refactor DatasetUrn to extend the base Urn
- [ ] When creating a Urn string, strip unsupported characters (introduces possibility of collision)
- [ ] Add a utility function to "uniqify" the Urn string by adding 3 numeric chars at the end (allows for up to a thousand collisions, which should be plenty)
