### ISSUE TITLE
Add API model tests

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#587]
Let's add tests to the models defined under [`marquez.api.models`](https://github.com/MarquezProject/marquez/tree/master/src/main/java/marquez/api/models).

## Issues

- [x] Add dataset request/response tests #588
- [x] Add namespace request/response tests #584
- [x] Add datasource request/response tests #585
- [x] Add job request/response tests #586

**Comment by wslulciuc** [comment]
@ravikamaraj, thanks for helping out with this epic! I've assigned all the issues to you 🚀💯

**Comment by wslulciuc** [comment]
@ravikamaraj, mind linking issues in future PRs as outlined in our [`CONTRIBUTING.md`](https://github.com/MarquezProject/marquez/blob/master/CONTRIBUTING.md)?

**Comment by wslulciuc** [comment]
Fixed #593

**Comment by wslulciuc** [comment]
Big shout out to @ravikamaraj for the help on closing this epic! 💯 🥇

**Comment by ravikamaraj** [comment]
> Big shout out to @ravikamaraj for the help on closing this epic! 💯 🥇

thank you :)
