### ISSUE TITLE
Add configurable sources in config.yml 

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#708]
Let's add support for configurable sources in `config.yml`. See [proposal](https://github.com/MarquezProject/marquez/issues/698) for full discussion.

### Issues

- [ ] Add column `qualifier` to **table** `sources` #705
- [ ] Add qualifier field to SourceMeta and Source #709
- [ ] Add `SourceRequest.qualifier` #706
- [ ] Add `sources` to `config.yml` #707

**Comment by Meehau** [comment]
Hi, that would be great. From our side, what we are missing are: MapR-FS distributed filesystem (similar to Hadoop FS) and MapR-DB distributed NoSQL database (similar to HBase). Assuming that there would be configurable data sources - this should be a non-issue, but if not then we would really need to add (hardcode?) these for now.

**Comment by julienledem** [comment]
@Meehau  We have decided to make Datasource type less constrained . It will now accept a general string.
