### ISSUE TITLE
Multi-module project structure

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#826]
In an effort to simplify getting started and contributing to Marquez, we are moving towards a multi-module project structure. This will also allow us to align official releases (`X.Y.Z`) across modules. The project will now contain the following modules:

* `spec` - defines the marquez API spec
* `docs` - main documentation
* `api` - core API used to collect metadata 
* `clients` - clients that implement the marquez API (`java`, `python`)
* `integrations` - integrations with external systems (`airflow`, `spark`) 
* `web` - web UI used to view metadata
* `chart` - helm chart
* `examples` - example usage of marquez (`airflow`, `spark`, etc)

### Tasks

- [x] Move [src/](https://github.com/MarquezProject/marquez/tree/main/src) to `api/`
- [x] Move [openapi.yml](https://github.com/MarquezProject/marquez/blob/main/docs/openapi.yml) to `spec/`
- [x] Move and deprecate [marquez-airflow](https://github.com/MarquezProject/marquez-airflow)
- [x] Move and deprecate [marquez-java](https://github.com/MarquezProject/marquez-java)
- [x] Move and deprecate [marquez-python](https://github.com/MarquezProject/marquez-python)
- [x] Move and deprecate [marquez-web](https://github.com/MarquezProject/marquez-web)
- [x] Move and deprecate [marquez-chart](https://github.com/MarquezProject/marquez-chart)
- [x] Move and deprecate [marquez-airflow-quickstart](https://github.com/MarquezProject/marquez-airflow-quickstart)
